CLASS zcl_abapgit_ortec_ser_cost DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_abapgit_ortec_ser_cost IMPLEMENTATION.
ENDCLASS.
