CLASS zcl_abapgit_ortec_ser_planner DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_abapgit_ortec_ser_planner IMPLEMENTATION.
ENDCLASS.
