CLASS zcl_abapgit_ortec_ser_orch DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_abapgit_ortec_ser_orch IMPLEMENTATION.
ENDCLASS.
